"""
Note:
    On Linux you need to run this as well: apt-get install portaudio19-dev
    The gpu extra supports Linux and Windows x64.
    You can see the used execution provider by enable debug log. see with_log.py
    ONNX Runtime 1.30 requires CUDA 13.x and cuDNN 9.x. The gpu extra installs
    compatible runtime wheels, and Kokoro preloads their DLLs before inference.
    An NVIDIA driver compatible with CUDA 13 is required; no driver is installed.

Setup:
    pip install -U kokoro-onnx[gpu] soundfile
    wget https://github.com/thewh1teagle/kokoro-onnx/releases/download/model-files-v1.1/kokoro-v1.0.onnx
    wget https://github.com/thewh1teagle/kokoro-onnx/releases/download/model-files-v1.1/voices-v1.0.bin

Run with Python:
    python examples/with_cuda.py

Run with uv (if you cloned the repo):
    uv run --extra gpu ./examples/with_cuda.py
"""

import os

import onnxruntime as ort
import soundfile as sf

from kokoro_onnx import Kokoro

os.environ["ONNX_PROVIDER"] = "CUDAExecutionProvider"
print("Available providers:", ort.get_available_providers())

kokoro = Kokoro("kokoro-v1.0.onnx", "voices-v1.0.bin")
print("Active providers:", kokoro.sess.get_providers())
samples, sample_rate = kokoro.create(
    "Hello. This audio generated by kokoro!", voice="af_sarah", speed=1.0, lang="en-us"
)
sf.write("audio.wav", samples, sample_rate)
print("Created audio.wav")
